channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::biopython=1.83
- conda-forge::pandas=2.2.2
- conda-forge::requests=2.31.0
- conda-forge::retry=0.9.2
- conda-forge::tqdm=4.66.4
- conda-forge::xmltodict=0.13.0
